name: CI

on:
  push:
  pull_request:

jobs:
  docker:
    name: Build and test docker image

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t nominatim
        working-directory: 3.6

      - name: Check import without mounts
        working-directory: .github/workflows
        run: |-
          docker run -i --rm \
            -e PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf \
            -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
            -p 8080:8080 \
            nominatim &
          sleep 45
          ./assert-non-empty-json "http://localhost:8080/search.php?q=avenue%20pasteur"

      - name: Check import with mount
        working-directory: .github/workflows
        run: |-
          docker run -i --rm \
            -e PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf \
            -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
            -v nominatim-config:/app/data \
            -v nominatim-postgres:/var/lib/postgresql/12/main \
            -p 8081:8080 \
            nominatim &
          sleep 45
          ./assert-non-empty-json "http://localhost:8081/search.php?q=avenue%20pasteur"

      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'mediagis' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image to Dockerhub
        if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'mediagis' }}
        run: |
          # we tag the image with the version number of nominatim but also
          # a second tag which adds the git commit ID so that you can refer
          # to a stable image
          docker tag nominatim mediagis/nominatim:3.6
          docker tag nominatim mediagis/nominatim:3.6-${{ github.sha }}
          docker image push --all-tags mediagis/nominatim

